version: '3'

services:
  app:
    restart: always
    build: app 
    container_name: slp_app
    links:
      - db:db 
    volumes:
      - ${PROJECT_PATH}/backend/backend:/usr/src/app
      - ${PROJECT_PATH}/backend/inbox/:/usr/src/inbox
      - ./app:/usr/src/run
    environment:
      - DEBUG='true'
      - PYTHONUNBUFFERED='true'
      - BACKEND_DB_POSTGRE_NAME=predictsuperleague
      - BACKEND_DB_POSTGRE_USER=root
      - BACKEND_DB_POSTGRE_PASSWORD=Predict123!
      - BACKEND_DB_POSTGRE_HOST=db
      - BACKEND_DB_POSTGRE_PORT=5432
    command: bash /usr/src/run/run.sh

  db:
    image: postgres
    container_name: slp_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Predict123!
      - POSTGRES_DB=predictsuperleague
    volumes:
      - ${PROJECT_PATH}/data:/var/lib/postgresql/data

  node:
    container_name: slp_node
    build: node
    environment:
      - NODE_ENV=development
    volumes:
      - ${PROJECT_PATH}/frontend:/usr/src/frontend
    command: bash /usr/src/run.sh

  web:
    container_name: slp_web
    restart: unless-stopped
    build: ./web
    links:
      - app:app
      - node:node
    volumes:
      - ${PROJECT_PATH}/backend/static:/usr/share/html/static
      - ${PROJECT_PATH}/backend/media:/usr/share/html/media
    ports:
      - "3000:80"
